### ISSUE TITLE
proxmox_kvm causes deprecation warning from Cloud-init when setting "ciuser"

### ISSUE THREAD

**Issue by DBS-ST-VIT** [ansible-collections/community.proxmox#107]
##### SUMMARY
When I set the ciuser using proxmox_kvm cloud-init prints the deprecation warning, that "'user' of type string is deprecated in 22.2 and scheduled to be removed in 27.2. Use 'users' list instead"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.general.proxmox_kvm

##### ANSIBLE VERSION
```
$ ansible --version
ansible [core 2.18.6]
  config file = /builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg
  configured module search path = ['/home/ci-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible-core/lib/python3.13/site-packages/ansible
  ansible collection location = /home/ci-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.4 (main, Jun  4 2025, 17:16:35) [GCC 12.2.0] (/opt/pipx/venvs/ansible-core/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list community.general
# /home/ci-user/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0 
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
CONFIG_FILE() = /builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg
DEFAULT_FORCE_HANDLERS(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = True
DEFAULT_HOST_LIST(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = ['/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/inventory/infrastructure']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/ansible.log
DEFAULT_PRIVATE_KEY_FILE(env: ANSIBLE_PRIVATE_KEY_FILE) = MASKED
DEFAULT_REMOTE_USER(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = MASKED
DEFAULT_TIMEOUT(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = 180
DEFAULT_VAULT_IDENTITY_LIST(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = MASKED
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 0
DISPLAY_SKIPPED_HOSTS(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = False
HOST_KEY_CHECKING(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = False
INTERPRETER_PYTHON(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = auto_silent
LOCALHOST_WARNING(/builds/evita/infrastructure/vm-templates/evita-gitlabrunner-vm-template/config/ansible_init.cfg) = False
GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
Debian

##### STEPS TO REPRODUCE

- Create a VM-Template which is configurable by your ansible setup and run the following task.
```yaml
- name: Cloud-init settings are configured
  throttle: 1
  community.general.proxmox_kvm
    node: "some_valid_node"
    api_host: "some_valid_api_host"
    api_user: "some_valid_user"
    api_token_id: "some_valid_token"
    api_token_secret: "some_valid_secret"
    name: "some_valid_vm_name"
    ciuser: "some_valid_user_name"
    cipassword: "some valid password"
```
- start the VM and wait for cloud-init to be done
```yaml
- name: Cloud-init settings are configured
  throttle: 1
  community.general.proxmox_kvm
    node: "some_valid_node"
    api_host: "some_valid_api_host"
    api_user: "some_valid_user"
    api_token_id: "some_valid_token"
    api_token_secret: "some_valid_secret"
    name: "some_valid_vm_name"
    state: "started"

- name: Wait for cloud-init to be done
  ansible.builtin.command: "cloud-init status"
  register: _cloud_init_result
  until:
    - _cloud_init_result.stdout is defined
    - '" done" in _cloud_init_result.stdout'
  retries: 10
  delay: 5
  changed_when: false
  failed_when: false
```
- print the logs:
```yaml
- name: Display cloud-init log file content
  ansible.builtin.debug:
    msg: "{{ _cloudinit_log['content'] | b64decode }}"
```

##### EXPECTED RESULTS
I expect to see no deprecation warning in the printed log.

##### ACTUAL RESULTS
Cloud-init prints the following deprecation warning:
lifecycle.py[DEPRECATED]: 'user' of type string is deprecated in 22.2 and scheduled to be removed in 27.2. Use 'users' list instead.
