### ISSUE TITLE
[community.proxmox.proxmox] 500 Internal Server Error: SSH public key validation error

### ISSUE THREAD

**Issue by RRohi** [ansible-collections/community.proxmox#113]
##### SUMMARY

After fiddling with the community.proxmox.promox module for hours to get it working, it looks like I've made it to the final boss. For whatever reason, I'm getting the following error: ``An error occurred: 500 Internal Server Error: SSH public key validation error``.
Not sure if this is a bug or a bug originating from this module but the module triggers it.

- I have installed my internal CA root certificates in the Ansible host and Proxmox.
- I changed the proxmox pve certificate. GUI doesn't warn about insecure certificate anymore, but I don't know if the API has a different certificate. Probably not.
- SSH keypair is generated using ssh-keygen.
- At first I didn't have pip-system-certs pip package installed, but I installed it and added my CA cert to ``~/PMX/lib/python3.11/site-packages/certifi/cacert.pem``. Didn't help.

I don't know what is being checked against what.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.proxmox.proxmox

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.18]
  config file = /root/Projects/Ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.proxmox 1.0.1
```

##### CONFIGURATION

```paste below
ANSIBLE_HOME(/root/Projects/Ansible/ansible.cfg) = /root/.ansible
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/root/Projects/Ansible/ansible.cfg) = warning
CONFIG_FILE() = /root/Projects/Ansible/ansible.cfg
DEFAULT_BECOME(/root/Projects/Ansible/ansible.cfg) = True
DEFAULT_FORKS(/root/Projects/Ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/root/Projects/Ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/root/Projects/Ansible/ansible.cfg) = ['/root/Projects/Ansible/Inventory/Hosts.yaml']
DEFAULT_PRIVATE_KEY_FILE(/root/Projects/Ansible/ansible.cfg) = /root/.ssh/remote
DEPRECATION_WARNINGS(/root/Projects/Ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/root/Projects/Ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/root/Projects/Ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/root/Projects/Ansible/ansible.cfg) = ~/PMX/bin/python3
```

##### OS / ENVIRONMENT

All hosts are Debian 12.

##### STEPS TO REPRODUCE

ansible-playbook proxmox.yml -vvvvv

Playbook (proxmox.yml)
```yaml
---
- name: Proxmox LXC Role.
  hosts: Proxmox
  become: true
  become_flags: '-s /bin/bash'
  become_method: su
  become_user: root

  tasks:
    - name: Import Proxmox role.
      ansible.builtin.import_role:
        name: Proxmox
```
Role (roles/Proxmox/tasks/main.yml)
```yaml
- name: Install cryptography pip package.
  ansible.builtin.pip:
    name:
      - pip-system-certs
      - proxmoxer
    virtualenv: /root/PMX

- name: Create a random but idempotent password.
  ansible.builtin.set_fact:
    password: "{{ lookup('ansible.builtin.password', '/root/root-' + ansible_facts['hostname'], seed=inventory_hostname) }}"

- name: Create a new LXC.
  become: true
  become_flags: '-s /bin/bash'
  become_method: su
  become_user: root
  community.proxmox.proxmox:
    api_host: 'pve.home.local'
    api_port: 8006
    api_token_id: 'svc-ansible'
    api_token_secret: '00000e02-5631-4006-a002-15912dc00000'
    api_user: 'svc-ansible@pam'
    cores: 1
    cpus: 1
    description: 'test vm'
    disk: 'Storage,size=6G'
    hostname: 'testcontainer'
    memory: 1024
    nameserver: '192.168.2.2'
    netif: "{'net0':'name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=2'}"
    node: 'pve'
    ostemplate: 'Images:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst'
    password: "{{ password }}"
    pubkey: '/files/keys/remote.pub'
    searchdomain: 'home.local'
    state: present
    swap: 0
    timezone: 'Europe/Tallinn'
    unprivileged: true
    update: true
    validate_certs: false #was true, didn't change the outcome
```

##### EXPECTED RESULTS

The expected outcome would be a new LXC in Proxmox named testcontainer.

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_community.proxmox.proxmox_payload_8azb3mug/ansible_community.proxmox.proxmox_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox.py", line 1714, in main
  File "/tmp/ansible_community.proxmox.proxmox_payload_8azb3mug/ansible_community.proxmox.proxmox_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox.py", line 771, in run
  File "/tmp/ansible_community.proxmox.proxmox_payload_8azb3mug/ansible_community.proxmox.proxmox_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox.py", line 880, in lxc_present
  File "/tmp/ansible_community.proxmox.proxmox_payload_8azb3mug/ansible_community.proxmox.proxmox_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox.py", line 1114, in new_lxc_instance
  File "/tmp/ansible_community.proxmox.proxmox_payload_8azb3mug/ansible_community.proxmox.proxmox_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox.py", line 1219, in create_lxc_instance
  File "/root/PMX/lib/python3.11/site-packages/proxmoxer/core.py", line 179, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PMX/lib/python3.11/site-packages/proxmoxer/core.py", line 170, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PMX/lib/python3.11/site-packages/proxmoxer/core.py", line 147, in _request
    raise ResourceException(
fatal: [pve.home.local]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "pve.home.local",
            "api_password": null,
            "api_port": 8006,
            "api_token_id": "svc-ansible",
            "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "svc-ansible@pam",
            "clone": null,
            "clone_type": "opportunistic",
            "cores": 1,
            "cpus": 1,
            "cpuunits": null,
            "description": "test vm",
            "disk": "Storage,size=6G",
            "disk_volume": null,
            "features": null,
            "force": false,
            "hookscript": null,
            "hostname": "testcontainer",
            "ip_address": null,
            "memory": 1024,
            "mount_volumes": null,
            "mounts": null,
            "nameserver": "192.168.2.2",
            "netif": {
                "net0": "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=2"
            },
            "node": "pve",
            "onboot": null,
            "ostemplate": "Images:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst",
            "ostype": "auto",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": null,
            "pubkey": "/files/keys/remote.pub",
            "purge": false,
            "searchdomain": "home.local",
            "startup": null,
            "state": "present",
            "storage": "local",
            "swap": 0,
            "tags": null,
            "timeout": 30,
            "timezone": "Europe/Tallinn",
            "unprivileged": true,
            "update": true,
            "validate_certs": false,
            "vmid": null
        }
    },
    "msg": "An error occurred: 500 Internal Server Error: SSH public key validation error"
}
```

**Comment by Thulium-Drake** [comment]
This error is not caused by the module itself, it's the API call returning that it's unable to validate the public key of the targeted host.

Can you check if you're able to ssh from the node you've set as `api_host` to the `node` as `root`? Proxmox utilizes SSH for some of the communication between hosts

**Comment by RRohi** [comment]
You're probably right. I thought about it later and it doesn't look like an SSH error, because I did have these earlier and those are pretty clear.

> Can you check if you're able to ssh from the node you've set as api_host to the node as root?

I don't think I understand. api_host and node are the same machine. One is FQDN, and the other is the hostname of the Proxmox host.

I can SSH from the Ansible host to Proxmox.

**Comment by RRohi** [comment]
Just remembered that I can check the remote server certificate.
Running the following command shows that the PMX service has the correct internal CA certificate.

`echo | openssl s_client -showcerts -servername pve.home.local -connect pve.home.local:8006 2>/dev/null | openssl x509 -inform pem -noout -text`

**Comment by Thulium-Drake** [comment]
The issue is not related to the API SSL certs :-) 

It still might be that Proxmox wants to SSH into the node to do stuff, can you check if you can run `ssh root@fqdn` and check for any errors with regards to host key validation?

**Comment by RRohi** [comment]
> The issue is not related to the API SSL certs :-)
> 
> It still might be that Proxmox wants to SSH into the node to do stuff, can you check if you can run `ssh root@fqdn` and check for any errors with regards to host key validation?

SSH is successful.

Edit0: By the way, the pip package install task in the role is successful, so Ansible is able to run tasks against the Proxmox host.

---

Edit1: I looked at how to use the Python proxmoxer package to manually log into my Proxmox host from the Ansible host and it was successful.
```python
#!/usr/bin/env python
from proxmoxer import ProxmoxAPI

prox = ProxmoxAPI("pve.home.local", user="svc-ansible@pam", token_name="svc-ansible", token_value="valid-token-here", verify_ssl=True)

print(prox.access.users.get())
```
It lists three Proxmox accounts.

---

Edit2: `journalctl -u ssh | tail -n 10` output on the Proxmox host after running `ansible-playbook proxmox.yml` on the Ansible host.
```
Jun 24 23:09:32 citadel sshd[3961698]: Accepted publickey for root from 192.168.2.8 port 40824 ssh2: ED25519 SHA256:X00t+0Jb000JlPXDYD0007GlEpw4qDv0001fzCWH00
Jun 24 23:09:32 citadel sshd[3961698]: pam_unix(sshd:session): session opened for user root(uid=0) by (uid=0)
Jun 24 23:09:32 citadel sshd[3961698]: pam_env(sshd:session): deprecated reading of user environment enabled
```
I don't know what the last line is, but it seems that the public key was accepted and the connection was successful. When I remove the community.proxmox.proxmox module from the playbook, the playbook runs against the Proxmox host without errors.

---

Edit3: Thought of running some other module from the community.proxmox collection and this was successful for example:
```yaml
- name: Test VM fetch.
  community.proxmox.proxmox_vm_info:
    api_host: 'pve.home.local'
    api_port: 8006
    api_token_id: 'svc-ansible'
    api_token_secret: '00000e02-5631-4006-a002-15912dc00000'
    api_user: 'svc-ansible@pam'
    node: pve
  register: vms
  tags: test

- name: Show VMs.
  ansible.builtin.debug:
    var: vms
  tags: test
```

**Comment by RRohi** [comment]
Holy ship!
It took me several hours to figure out how to specify the token information and several DAYS to figure out some obscure SSH public key error, which turned out to come from the pubkey parameter.
I inserted the pubkey file path, instead of the key itself, thinking it would surely read the file contents from the file.

The examples and info on the ([Ansible collection](https://docs.ansible.com/ansible/devel/collections/community/proxmox/proxmox_module.html#ansible-collections-community-proxmox-proxmox-module)) page are severely lacking.
For whatever reason, some parameters aren't even mentioned in the examples.

My initial post has the playbook I had at first, this is what ended up working:
(Change in the netif parameter value is not related to the problems I had, I got it working and didn't want DHCPv6 to have DHCP enabled)
```yaml
- name: Create a new LXC.
   community.proxmox.proxmox:
    api_host: 'pve.home.local'
    api_port: 8006
    api_token_id: 'svc-ansible'
    api_token_secret: '00000e02-5631-4006-a002-15912dc00000'
    api_user: 'svc-ansible@pam'
    cores: 1
    cpus: 1
    description: 'test vm'
    disk_volume:
      size: 6
      storage: Storage
    hostname: 'testcontainer'
    memory: 1024
    nameserver: '192.168.2.2'
    netif: "{'net0':'name=eth0,ip=dhcp,bridge=vmbr0,tag=2'}"
    node: 'pve'
    ostemplate: 'Images:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst'
    password: "{{ password }}"
    pubkey: 'ssh-ed25519 string Ansible@Ansihost'
    searchdomain: 'home.local'
    state: present
    swap: 0
    timezone: 'Europe/Tallinn'
    unprivileged: true
    update: true
    validate_certs: true
```
