### ISSUE TITLE
Error: 'ProxmoxNodeInfoAnsible' object has no attribute 'module'

### ISSUE THREAD

**Issue by AndyHowell** [ansible-collections/community.proxmox#114]
##### SUMMARY
community.proxmox.proxmox_node_info returns error  'ProxmoxNodeInfoAnsible' object has no attribute 'module'
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/andy/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/andy/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.proxmox 1.0.1  

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.proxmox 1.0.1  

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
EDITOR(env: EDITOR) = vim

```

##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.2 LTS"

##### STEPS TO REPRODUCE

```yaml
---
- hosts: my-host
  tasks:
    - name: List existing nodes
      community.proxmox.proxmox_node_info:
        api_host: my-host
        api_user: root@pam
        api_token_id: "terraform@pam!terraform"
        api_token_secret: "my-token"
      register: proxmox_nodes

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ proxmox_nodes }}"

```

##### EXPECTED RESULTS

node info

##### ACTUAL RESULTS

Fails with stack trace.

```paste below

I attached the full log as error.txt

The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.proxmox.plugins.modules.proxmox_node_info', init_globals=dict(_module_fqn='ansible_collections.community.proxmox.plugins.modules.proxmox_node_info', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox_node_info.py", line 139, in <module>
  File "/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox_node_info.py", line 130, in main
  File "/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/module_utils/proxmox.py", line 81, in __init__
AttributeError: 'ProxmoxNodeInfoAnsible' object has no attribute 'module'
fatal: [tanuki]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_9.6p1 Ubuntu-3ubuntu13.12, OpenSSL 3.0.13 30 Jan 2024\r\ndebug1: Reading configuration data /home/andy/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /home/andy/.ssh/config line 57: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/andy/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/andy/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/andy/.ansible/cp/5c55381472'\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 124181\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet_timeout: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to tanuki closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1750707230.8079174-124221-165757546457857/AnsiballZ_proxmox_node_info.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.proxmox.plugins.modules.proxmox_node_info', init_globals=dict(_module_fqn='ansible_collections.community.proxmox.plugins.modules.proxmox_node_info', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox_node_info.py\", line 139, in <module>\r\n  File \"/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/modules/proxmox_node_info.py\", line 130, in main\r\n  File \"/tmp/ansible_community.proxmox.proxmox_node_info_payload_m8717xxy/ansible_community.proxmox.proxmox_node_info_payload.zip/ansible_collections/community/proxmox/plugins/module_utils/proxmox.py\", line 81, in __init__\r\nAttributeError: 'ProxmoxNodeInfoAnsible' object has no attribute 'module'\r\n",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",
    "rc": 1
}

[error.txt](https://github.com/user-attachments/files/20871364/error.txt)

```

**Comment by felixfontein** [comment]
Can you check your version of proxmoxer? In a similar issue (#110) that seems to have been the problem.

There's definitely also something to fix in the module though, since it shouldn't crash this way...

**Comment by AndyHowell** [comment]
> Can you check your version of proxmoxer? In a similar issue ([#110](https://github.com/ansible-collections/community.proxmox/issues/110)) that seems to have been the problem.
> 
> There's definitely also something to fix in the module though, since it shouldn't crash this way...

I had 2.0.1 installed. I just setup a python venv and installed 2.2. I get the same results. I suspected proxmoxer might be an issue. I ran a simple test on both the 2.0.1 and 2.2:

```
from proxmoxer import ProxmoxAPI

proxmox = ProxmoxAPI('my-host', user='root@pam', password='pass', verify_ssl=False)

for node in proxmox.nodes.get():
    for vm in proxmox.nodes(node["node"]).qemu.get():
        print(f"{vm['vmid']}. {vm['name']} => {vm['status']}")
```

That worked under both versions. Happy to debug further. Let me know if there is something you would like me to try.

Thanks, Andy

**Comment by AndyHowell** [comment]
I was wrong about the proxmoxer version. I thought that it was supposed to be installed on my local machine. The version that is installed on my proxmox machine is 1.2. I created a virtual env under  the ansible user ( named ansible ) and installed:

```
pyenv/bin/python3 -m pip install proxmoxer
Collecting proxmoxer
  Downloading proxmoxer-2.2.0-py3-none-any.whl (19 kB)
```
I tried to debug on the proxmox machine by running this on the ansible machine:

```
export ANSIBLE_KEEP_REMOTE_FILES=1
ansible-playbook get_proxmox_info.yaml -i ../inventory  -u ansible
```
on the proxmox machine I switched to a directory under ~/.ansible/tmp/<xxxx> directory and ran

```
python3 AnsiballZ_proxmox_node_info.py explode
python3 AnsiballZ_proxmox_node_info.py execute
```
Without the proxmoxer 2.0, it fails with:
```
File "/home/ansible/.ansible/tmp/ansible-tmp-1750818118.1629958-68022-48499720583870/debug_dir/ansible_collections/community/proxmox/plugins/module_utils/proxmox.py", line 82, in __init__
    self.module.fail_json(f'Requires proxmoxer 2.0 or newer; found version {proxmoxer_version}')
```
The proxmoxer_version is set to 1.2. So its not picking up the version is installed under the virtualenv. I don't know why. Its been a long time since I did any python debugging, I'm a bit rusty.

However, the ```python3 AnsiballZ_proxmox_node_info.py execute``` under the venv is now giving me an authentication error. I'll investigate that tomorrow. Progress.

**Comment by felixfontein** [comment]
Generally modules don't run in a venv even on localhost unless you make sure to tell Ansible to do so, likely with setting `ansible_python_interpreter` to the right value.

**Comment by AndyHowell** [comment]
Felix,

Thanks. Got this working. Last sticking point was the difference between how terraform specifies the token id, and how proxmoxer does it.  Terraform has the user@realm!token-id as opposed to just token-id.

I added a commented test script. Feel free to add to docs if it helps. 
get_proxmox_info.yaml

```
---
# on proxmox host:
#  apt-get install python3-venv
#  apt-get install python3-virtualenv
#  apt-get install python3-pip
#
# as ansible user. (linux user, not proxmox user. ie added with useradd)
#  - Create a new python virtual environment for proxmoxer 2.0.
#  - Proxmox virtualenv pyenv
#   add to .bashrc
#     source ~/pyenv/bin/activate
#   re-login or source activate
# 
#   python -m pip install proxmoxer
#   python -m pip install requests
#
#   The following are under the virtual environment
#   python -m pip list
#
# Package            Version
# ------------------ ---------
# certifi            2025.6.15
# charset-normalizer 3.4.2
# idna               3.10
# pip                23.0.1
# proxmoxer          2.2.0
# requests           2.32.4
# setuptools         66.1.1
# urllib3            2.5.0
# wheel              0.38.4

# Under the proxmox_node_info:
#   api_host: Proxmox node name
#   api_user: user created through proxmox web gui
#   api_token_id: The id you gave when creating the API token
#                 Unlike terraform, it doest not include the 
#                 user@realm
#   api_token_secret: The api secret, copied from the Web API Token -> add
#
# For this example, I used my existing terraform user, and created a new 
# API token.
#
## Run with:
# ansible-playbook get_proxmox_info.yaml -i inventory  -u ansible
#
- hosts: <your proxmox host>
  vars:
    # Tell ansible to use our environment so we pick up the promoxer 2.x. 
    # PVE 8.4.1 is using proxmoxer 1.2
    ansible_python_interpreter: /home/ansible/pyenv/bin/python
  tasks:
    - name: List existing nodes
      community.proxmox.proxmox_node_info:
        api_host: "<your proxmox host"
        api_user: "terraform@pam"
        api_token_id: "<your token name here>"
        api_token_secret: "<your secret here>"
      register: proxmox_nodes

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ proxmox_nodes }}"
```

**Comment by Thulium-Drake** [comment]
It sounds to me that this would be nice to add to some sort of guide. @felixfontein is there any location in the collection where we can store these? Or is it sufficient to 'just' create a folder guides and drop a `md` file in there?

**Comment by AndyHowell** [comment]
As I'm learning ansible, I'm happy to contribute to documentation.  I searched for a way to bootstap ansible and came across this:

https://github.com/rlaager/ansible-bootstrap/tree/master

I cloned that and modified the roles/bootstrap/tasks/main.yml make a python virtual environment similar to what I mentioned above. If bootstrapping a proxmox machine it installs proxmoxer 2.x.

```
# This must be the first task for bootstrapping!
# 
# If requiretty is set on the remote host, the bootstrapping itself will
# fail because of pipelining.  Instead, we force the use of paramiko, which
# does not do pipelining.  Alternatively, we could remove the paramiko
# connection specification, but then users would have to run:
#   ANSIBLE_SSH_PIPELINING=0 ansible-playbook playbooks/bootstrap.yaml ...
- name: remove requiretty from sudoers
  connection: paramiko
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: ^\s*Defaults\s+requiretty$
    validate: /usr/sbin/visudo -cf %s
  when: ansible_connection != "local"

- name: explicitly gather facts
  setup:

- name: install SELinux dependencies
  yum:
    name: "{{ bootstrap_packages }}"
    state: present
  vars:
    bootstrap_packages:
      - libselinux-python
      - policycoreutils-python
  when: ansible_facts["os_family"] == "RedHat"

# NOTE: It seems weird to run this so late, since other things have assumed
# NOTE: that sudo exists.  However, if this matters (i.e. sudo is not
# NOTE: installed), then the user MUST specify a become_method on the command
# NOTE: line for this role to work at all, so it doesn't really matter when
# NOTE: this particular task is run.
- name: install sudo
  apt:
    name: sudo
    state: present
    cache_valid_time: 3600
    force_apt_get: yes
  when: ansible_facts["os_family"] == "Debian"

- name: allow ansible user to have passwordless sudo
  lineinfile:
    path: /etc/sudoers.d/ansible
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    # Older systems require this to be 0440 or sudo breaks.
    mode: 0440
    create: yes
    validate: /usr/sbin/visudo -cf %s

- name: add ansible user and set groups
  user:
    name: ansible
    # On RedHat systems, we put the ansible user in the wheel group to
    # work-around cPanel's open file limit of 100.  Mitogen uses file
    # descriptors 100 and 101 for internal purposes.  See:
    # https://github.com/dw/mitogen/issues/644
    groups:
      "{{ 'wheel' if ansible_facts['os_family'] == 'RedHat' else '' }}"
    home: "/home/ansible"

- name: create ansible's authorized_keys
  become: yes
  become_user: "{{ 'root' if ansible_check_mode else 'ansible' }}"
  authorized_key:
    user: ansible
    path: "/home/ansible/.ssh/authorized_keys"
    key: |
      {{ lookup('file', 'ansible.ed25519.key.pub') }}
      {{ lookup('file', 'ansible.rsa.key.pub') }}
    exclusive: yes

# This must be after setting up passwordless sudo and the authorized_keys.
- name: remove ansible's password
  user:
    name: ansible
    password: "*"

- name: Install python virtual environment packages
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-pip-whl
      - python3-virtualenv
  when: ansible_facts["os_family"] == "Debian"

- name: New directory for python virtual environments
  become_user: ansible
  ansible.builtin.file:
    path: /home/ansible/python_venv
    state: directory
    mode: u+rwx,g+rx,o+rx

- name: Create virtual environment for the current ansible version
  become_user: ansible
  ansible.builtin.command: python3 -m venv "ansible{{ ansible_version.full }}"
  args:
    chdir: /home/ansible/python_venv
    creates: /home/ansible/python_venv/ansible{{ ansible_version.full }}

- name: Check if this is a proxmox machine
  ansible.builtin.stat:
    path: /etc/pve
  register: pve_status

- name: Install proxmoxer and request on promox machines.
  # ansible promox module requires 2.0 or greater
  ansible.builtin.pip:
    name:
      - proxmoxer>=2.0
      - requests
    virtualenv: "/home/ansible/python_venv/ansible{{ ansible_version.full }}"
  when: "pve_status.stat.exists"

- name: Add symlink to point to latest environment for ansible
  # make this so when we have an interactive login under ansible, we see the
  # latest environment
  become_user: ansible
  ansible.builtin.file:
    src: "/home/ansible/python_venv/ansible{{ ansible_version.full }}"
    dest: "/home/ansible/python_venv/latest"
    state: link

- name: Update ansible .bashrc to use the latest python environment
  # Note: This is only for interactive logins. For playbooks we need
  # to set
  # vars:
  #     # Tell ansible to use our environment so we pick up the promoxer 2.x.
  #     # PVE 8.4.1 is using proxmoxer 1.2
  #     ansible_python_interpreter: /home/ansible/python_venv/ansible{{ ansible_version.full }}/bin/python
  ansible.builtin.lineinfile:
    path: /home/ansible/.bashrc
    line: source ~/python_venv/latest/bin/activate
    state: present
    insertafter: EOF
```

There may be better ways to do this, but this got me going. One downside of this is the need to specify ansible_python_interpreter in your own playbooks. I've only done it for Debian in this first pass.

**Comment by felixfontein** [comment]
> It sounds to me that this would be nice to add to some sort of guide. [@felixfontein](https://github.com/felixfontein) is there any location in the collection where we can store these? Or is it sufficient to 'just' create a folder guides and drop a `md` file in there?

If you want that documention to show up on the docsite (https://docs.ansible.com/ansible/devel/collections/community/proxmox/), you'll need to use RST and put it in docs/docsite/rst. More infos here: https://ansible.readthedocs.io/projects/antsibull-docs/collection-docs/#adding-extra-documentation

Examples:
- https://github.com/ansible-collections/community.sops/blob/main/docs/docsite/extra-docs.yml (section and filename for guide)
- https://github.com/ansible-collections/community.sops/blob/main/docs/docsite/rst/guide.rst (the guide itself)

**Comment by felixfontein** [comment]
It might be helpful to setup https://github.com/ansible-community/github-docs-build first so you have a GitHub Pages based docsite, and a process which builds test docsites for PRs so you can see directly what you're creating without having to build a docsite on your machine. community.general doesn't have it (since a docsite for it would be pretty large, and building it is pretty slow), but 'my' other collections have it, like community.sops:
- https://github.com/ansible-collections/community.sops/blob/main/.github/workflows/docs-pr.yml
- https://github.com/ansible-collections/community.sops/blob/main/.github/workflows/docs-push.yml

If you want I can try setting this up this evening or so...

**Comment by Thulium-Drake** [comment]
Thanks for the info, I'm all for creating more documentation, but for now I'm happy to first start making the documents and when we have acquired some guides we'll look into setting up the docsite.

Feels a bit pointless to set this up for a single guide 😅

**Comment by felixfontein** [comment]
> Feels a bit pointless to set this up for a single guide 😅

You'd also see the rendered module/plugin docs, which can also be helpful when trying to improve them, so it's for more than just the guide.

**Comment by agross** [comment]
The previous modules in the community.general collection required proxmoxer 1.x on the target host. Since I usually target the PVE hosts directly installing proxmoxer was easy using before any `community.general.proxmox*` module invocation:

```yaml
- name: Ensure proxmoxer is available
  ansible.builtin.package:
    name: python3-proxmoxer
    state: present
```

Unfortunately, the latest version of proxmoxer available on PVE 8.4 is 1.2.0, which is incompatible with the collection provided here:

```sh
$ apt info python3-proxmoxer
Package: python3-proxmoxer
Version: 1.2.0-2
```

How is one supposed to use this collection's modules without jumping through venv hoops (I'm not involved with Python in my day job)? Why does this collection depend on a version of proxmoxer that is not available on Proxmox VE itself?

**Comment by felixfontein** [comment]
Out of curiosity: why can you only install proxmoxer <= 1.2.0 on PVE 8.4? PVE 8.4 seems to be based on Debian Bookworm, whose native Python 3 version is 3.11 (https://packages.debian.org/bookworm/python3). With pip (https://packages.debian.org/bookworm/python3-pip) you should be able to install newer proxmoxer versions as well, the latest proxmoxer release requires Python >= 3.8, which 3.11 definitely satisfies.

**Comment by agross** [comment]
The latest "system" package `python3-proxmoxer` provided by apt is 1.2.0 and this is what I used previously.

With pip I am now forced to either install proxmoxer into venv and mess with ansible's Python interpreter path or go the scary route and `--break-system-packages`.

I have to admit I'm not a big fan of how Python handles dependencies. I feel like both methods outlined above have downsides (messing with paths vs deliberately "breaking" the system, referring to some PEP standard that non-Python developers first need to familiarize themselves with).

I am also astonished that the maintainers here force that breaking change upon their users without providing any guidance on how to prepare the systems that the collection's modules are targeting.

**Comment by AndyHowell** [comment]
> The latest "system" package `python3-proxmoxer` provided by apt is 1.2.0 and this is what I used previously.
> 
> With pip I am now forced to either install proxmoxer into venv and mess with ansible's Python interpreter path or go the scary route and `--break-system-packages`.

The "break something" fear was why I ended up installing a python environment under a user "ansible". Once I got the bootstrap playbook above working, it was fairly transparent. It does require setting the ansible_python_interpreter variable. 

As far as I can tell, there are no other packages that actually depend on proxmoxer:

```
apt-cache rdepends python3-proxmoxer
python3-proxmoxer
Reverse Depends:
```
Looking at proxmoxer dependencies, it says:
```
apt-cache depends python3-proxmoxer
python3-proxmoxer
  Depends: <python3:any>
    python3
  Recommends: python3-requests
  Recommends: python3-paramiko
```
I think 2.x actually requires 'requests'

So after going through all the work to setup a virtual environment, I may actually have been fine just doing the pip install.

Anyhow, here is my current working example. Its tweeked a bit from my previous post, as I change the path to the virtual environment, and added some more comments. Hope this helps.

```
--
# on proxmox host:
#  apt-get install python3-venv
#  apt-get install python3-virtualenv
#  apt-get install python3-pip
#
# as ansible user. (linux user, not proxmox user. ie added with useradd)
#  - Create a new python virtual environment for proxmoxer 2.0.
#  - I put it is under:
#       /home/ansible/python_venv/ansible{{ ansible_version.full }}/bin/python
#   mkdir python_env
#   cd python_env
#   python3 -m virtualenv ansible2.18.6
#   add to .bashrc
#     source ~/python_env/ansible2.18.6/bin/activate
#   re-login or source activate
#
#   Added it to .basherc is just so you have the python environment when
#   manually logging in as ansible. In a playbook, you need to specify
#   ansible_python_path. See below.
#
#   Now install proxmoxer and requests:
#   python3 -m pip install proxmoxer
#   python3 -m pip install requests
#
#   The following are under the virtual environment
#   pythoni3 -m pip list
#
# Package            Version
# ------------------ ---------
# certifi            2025.6.15
# charset-normalizer 3.4.2
# idna               3.10
# pip                23.0.1
# proxmoxer          2.2.0
# requests           2.32.4
# setuptools         66.1.1
# urllib3            2.5.0
# wheel              0.38.4

# Make a vault, proxmoxhost_secrets.yaml, for example, with the following info
#   api_host: Proxmox node name
#   api_user: user created through proxmox web gui
#   api_token_id: The id you gave when creating the API token
#                 Unlike terraform, it doest not include the 
#                 user@realm
#   api_token_secret: The api secret, copied from the Web API Token -> add
#
#  For example:
#
#  pve_host: "tanuki"
#  pve_api_user: "terraform@pam"
#  pve_api_token_id: "new"
#  pve_api_token_secret: "1234xxxxyyyyzzzzz"
#
# For this example, I used my existing terraform user, and created a new 
# API token.
#
# Run with:
# ansible-playbook -i inventory -u ansible --ask-vault-pass -e @proxmoxhost_secrets.yaml get_proxmox_info.yaml
# 
- hosts: "{{ pve_host }}"
  vars:
    # Tell ansible to use our environment so we pick up the promoxer 2.x. 
    # PVE 8.4.1 ships proxmoxer 1.2
    ansible_python_interpreter: /home/ansible/python_venv/ansible{{ ansible_version.full }}/bin/python
  tasks:
    - name: List existing nodes
      community.proxmox.proxmox_node_info:
        api_host: "{{ pve_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
      register: proxmox_nodes

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ proxmox_nodes }}"
```

**Comment by agross** [comment]
IMHO, my playbook's proxmox role should be self-sufficient: It should install the required dependencies itself. We also do not use a single "ansible" user; as a team working on the infrastructure every engineer has an own account.

Of course, one could create the venv globally, like in `/usr/lib/python-just-for-use-with-ansible-and-proxmox`, even automatically:

```yaml
- name: Ensure pip and venv are installed
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-venv

- name: Install proxmoxer and requests
  ansible.builtin.pip:
    name: 
      - promoxer
      - requests
    virtualenv: /usr/lib/python-just-for-use-with-ansible-and-proxmox
    virtualenv_command: "{{ ansible_python.executable }} -m venv"
```

The above modules would still need to run with the default/system Python because there is that instant in time when Ansible has never touched the PVE host before and the venv does not exist.

Before you could execute the first `community.proxmox` module, the Python path would need to change to point to the venv:

```yaml
- name: Use special Python to be able to use community.proxmox modules
  ansible.builtin.set_fact:
    ansible_python_interpreter: >-
      /usr/lib/python-just-for-use-with-ansible-and-proxmox/bin/python3
```

This ordering requirement will essentially break your ability to use `ansible-playbook --start-at-task` to start execution deeply into your proxmox role, which will become a chore when you develop your role.

So again, I wonder: Is this really what the maintainers here had in mind when they decided to take the proxmoxer 2.x dependency? Is there a better way that I just do not see?
