### ISSUE TITLE
proxmox_pool failure on existing poolid

### ISSUE THREAD

**Issue by fdziarmagowski** [ansible-collections/community.proxmox#116]
##### SUMMARY

community.proxmox.proxmox_pool fails on an existing poolid

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.proxmox.proxmox_pool

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.6]
  config file = None
  configured module search path = ['/home/freddy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/freddy/.local/share/pipx/venvs/ansible/lib/python3.13/site-packages/ansible
  ansible collection location = /home/freddy/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/freddy/.local/bin/ansible
  python version = 3.13.5 (main, Jun 21 2025, 01:04:42) [GCC 14.2.1 20250405] (/home/freddy/.local/share/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.proxmox 1.0.1
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
EDITOR(env: EDITOR) = nvim

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Linux 6.15.x (Void), Python 3.13.x, Proxmox 8.4.1
```paste below
# pipx list --include-injected
venvs are in /home/freddy/.local/share/pipx/venvs
apps are exposed on your $PATH at /home/freddy/.local/bin
manual pages are exposed at /home/freddy/.local/share/man
   package ansible 11.7.0, installed using Python 3.13.5
    - ansible
    - ansible-community
    - ansible-config
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
    Injected Packages:
      - boto3 1.38.42
      - distlib 0.3.9
      - jsonpatch 1.33
      - kubernetes 33.1.0
      - netaddr 1.3.0
      - passlib 1.7.4
      - proxmoxer 2.2.0
      - tomli-w 1.2.0
   package ansible-lint 25.6.1, installed using Python 3.13.5
    - ansible-lint
```

##### STEPS TO REPRODUCE

```yaml
    - name: Create a new Proxmox VE pool
      community.proxmox.proxmox_pool:
        api_host: "{{ api_host }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        api_user: "{{ api_user }}"
        poolid: "{{ poolid }}"
        comment: foo - "{{ poolid }}"
        state: present
      # ignore_errors to WORKAROUND for
      # "Failed to create pool with ID stable: 500 Internal Server Error:
      #  create pool failed: pool 'stable' already exists"
      ignore_errors: true
```

##### EXPECTED RESULTS

It should not fail.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create pool with ID stable: 500 Internal Server Error: create pool failed: pool 'stable' already exists"}
```

**Comment by Thulium-Drake** [comment]
I'm unable to recreate this issue, did you check if the user has enough permissions to create a pool? And since you're using a token, that you either didn't enable privilege separation on the token or pass the token enough privileges as well?

I tested it with the following play:

```
---
- name: 'Create pool'
  hosts: 'localhost'
  connection: 'local'
  become: false
  gather_facts: false
  vars:
    pve_password: 'ssshhhhh'
    pve_user: 'ansible@pve'
    pve_server: 'lab.example.nl'
  tasks:
    - name: Create pool
      community.proxmox.proxmox_pool:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_password }}"
        api_host: "{{ pve_server }}"
        poolid: testpoolmodule
        comment: testing a module
        state: 'present'
      loop:
        - 1 
        - 2 
    - name: Delete pool
      community.proxmox.proxmox_pool:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_password }}"
        api_host: "{{ pve_server }}"
        poolid: testpoolmodule
        state: 'absent'
      loop:
        - 1                         
        - 2    
```

```
PLAY [Do pool stuff] **********************************************************************************************************************************

TASK [Create pool] *********************************************************************************************************************************
changed: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [Delete pool] *********************************************************************************************************************************
changed: [localhost] => (item=1)
ok: [localhost] => (item=2)

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

**Comment by fdziarmagowski** [comment]
@Thulium-Drake of course I have required permissions. This about an _existing_ pool not a new one.

**Comment by Thulium-Drake** [comment]
I get that, hence why I had the task run twice in a loop, for both creating and deletion.

**Comment by fdziarmagowski** [comment]
@Thulium-Drake Glad to hear it works for you.
```
changed: [127.0.0.1] => (item=1) => {"ansible_loop_var": "item", "changed": true, "item": 1, "msg": "Pool test-pool successfully created", "poolid": "test-pool"}
failed: [127.0.0.1] (item=2) => {"ansible_loop_var": "item", "changed": false, "item": 2, "msg": "Failed to create pool with ID test-pool: 500 Internal Server Error: create pool failed: pool 'test-pool' already exists"}
```

**Comment by Thulium-Drake** [comment]
As mentioned earlier, I am unable to reproduce this on my end. The API on your server gives the error, I also to create pools with different casing and the use of hypens, underscores and numbers (see below).

I ran this playbook with the collection version 1.2.0 and the following:

```
root@lab:~# pveversion 
pve-manager/8.4.1/2a5fa54a8503f96d (running kernel: 6.8.12-11-pve)
```

```
   package ansible-core 2.18.7 (ansible-core_2-18), installed using Python 3.13.2
    - ansible
    - ansible-config
    - ansible-config_2-18
    - ansible-console
    - ansible-console_2-18
    - ansible-doc
    - ansible-doc_2-18
    - ansible-galaxy
    - ansible-galaxy_2-18
    - ansible-inventory
    - ansible-inventory_2-18
    - ansible-playbook
    - ansible-playbook_2-18
    - ansible-pull
    - ansible-pull_2-18
    - ansible-test
    - ansible-test_2-18
    - ansible-vault
    - ansible-vault_2-18
    - ansible_2-18
    Injected Packages:
      - ansible-merge-vars 5.0.0
      - ara 1.7.2
      - dnspython 2.7.0
      - jmespath 1.0.1
      - netaddr 1.3.0
      - passlib 1.7.4
      - proxmoxer 2.2.0
      - python-dateutil 2.9.0.post0
      - pytz 2025.2
```

```
---
- name: 'Create pool'
  hosts: 'localhost'
  connection: 'local'
  become: false
  gather_facts: false
  vars:
    pve_password: 'ssshhhh'
    pve_user: 'ansible@pve'
    pve_server: 'lab.example.nl'
    proxmox_pools:
      - pool
      - pool123
      - pool-123
      - pool_123
      - Pool123
      - Pool-123
      - Pool_123

  tasks:
    - name: Create pool
      community.proxmox.proxmox_pool:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_password }}"
        api_host: "{{ pve_server }}"
        name: "{{ item }}"
        comment: "Pool {{ item }}"
        state: 'present'
      loop: "{{ proxmox_pools + proxmox_pools }}"

    - name: Wait a bit
      ansible.builtin.pause:
        seconds: 10

    - name: Delete pool
      community.proxmox.proxmox_pool:
        api_user: "{{ pve_user }}"
        api_password: "{{ pve_password }}"
        api_host: "{{ pve_server }}"
        name: "{{ item }}"
        state: 'absent'
      loop: "{{ proxmox_pools + proxmox_pools }}"
```

```
$ runansible -p playground proxmox_pool.yml

PLAY [Create pool] ****************************************************************************************************

TASK [Create pool] ****************************************************************************************************
changed: [localhost] => (item=pool)
changed: [localhost] => (item=pool123)
changed: [localhost] => (item=pool-123)
changed: [localhost] => (item=pool_123)
changed: [localhost] => (item=Pool123)
changed: [localhost] => (item=Pool-123)
changed: [localhost] => (item=Pool_123)
ok: [localhost] => (item=pool)
ok: [localhost] => (item=pool123)
ok: [localhost] => (item=pool-123)
ok: [localhost] => (item=pool_123)
ok: [localhost] => (item=Pool123)
ok: [localhost] => (item=Pool-123)
ok: [localhost] => (item=Pool_123)

TASK [Wait a bit] *****************************************************************************************************
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Delete pool] ****************************************************************************************************
changed: [localhost] => (item=pool)
changed: [localhost] => (item=pool123)
changed: [localhost] => (item=pool-123)
changed: [localhost] => (item=pool_123)
changed: [localhost] => (item=Pool123)
changed: [localhost] => (item=Pool-123)
changed: [localhost] => (item=Pool_123)
ok: [localhost] => (item=pool)
ok: [localhost] => (item=pool123)
ok: [localhost] => (item=pool-123)
ok: [localhost] => (item=pool_123)
ok: [localhost] => (item=Pool123)
ok: [localhost] => (item=Pool-123)
ok: [localhost] => (item=Pool_123)

PLAY RECAP ************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Can you also run this playbook against your system and compare the output?
