### ISSUE TITLE
Proxmox: "net" do not configure network card

### ISSUE THREAD

**Issue by felixhopfauf** [ansible-collections/community.proxmox#21]
##### SUMMARY
Can't set any configuration with the parameter net in "proxmox_kvm"
I can see my options in proxmox Syslog but nothing will be configured.

Using latest repo from github

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

proxmox_kvm
##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/felix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/felix/.local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
""
```

##### OS / ENVIRONMENT

Debian 10 WSL on Windows 10 20H2

##### STEPS TO REPRODUCE

```yaml
- name: Create VM
  community.general.proxmox_kvm:
    api_user: "{{prox_user}}"
    api_password: "{{prox_pass}}"
    api_host: "{{prox_host}}"
    node: "{{prox_host}}"
    name: "{{item.name}}"
    clone: "{{template_name}}"
    newid: "{{item.id}}"
    memory: "{{item.ram}}"
    sockets: "{{vm_sockets}}"
    cores: "{{item.cores}}"
    net: {"net0":"virtio=32:5F:B4:35:16:0F,bridge=vmbr1"}
    cpu: host
    scsihw: virtio-scsi-pci
    agent: yes
    full: "{{ vm_full_clone }}"
    proxmox_default_behavior: no_defaults
  with_items: "{{vms}}"
  register: vmsinfo
```

##### EXPECTED RESULTS

Network card of vm will use "vmbr1" and mac address seen in config

##### ACTUAL RESULTS

It doesn't matter what I provide through the net option, it will be ignored:

Syslog Output: 

...memory=2048 sockets=1 cores=2 net={'net0': 'virtio=32:5F:B4:35:16:0F,bridge=vmbr1'} cpu=host scsihw=virtio-scsi-pci agent=True full=False...

```paste below

```

**Comment by p0rtL6** [comment]
Another solution is to update NIC settings with the `proxmox_kvm` module using the `update_unsafe` option as per the [ansible documentation](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html#ansible-collections-community-general-proxmox-kvm-module-parameter-vmid).

Example from docs:
```
- name: Update VM configuration (incl. unsafe options)
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: secret
    api_host: helldorado
    name: spynal
    node: sabrewulf
    cores: 8
    memory: 16384
    net:
      net0: virtio,bridge=vmbr1
    update: true
    update_unsafe: true # <- required
```
