### ISSUE TITLE
Proxmox CD Media management

### ISSUE THREAD

**Issue by damo2929** [ansible-collections/community.proxmox#33]
### Summary

HI all 
am looking at how I can manage ISO media using the proxmox kvm module

the proxmox web UI lets you set the Cdrom drive to be empty by setting the interface to "none,media=cdrom"

when I set the same using the proxmox_kvm module and setting the update nothing changes.

```
     - name: update VM configuration
       community.general.proxmox_kvm:
          api_user: "{{ proxmox_user }}"
          api_password: "{{ proxmox_password }}"
          api_host: "{{ proxmox_api_ip }}"
          name: "{{ inventory_hostname }}"
          node: "b550"
          sata:
             sata0: "none,media=cdrom"
          update: yes
```

how is it support to be done?

### Issue Type

Documentation Report

### Component Name

proxmox_kvm

### Ansible Version

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.10 (main, Feb  9 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 2.11.3
  libyaml = True

### Community.general Version

[ansible@Ansible ansible]$ ansible-galaxy collection list community.general

# /usr/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.5.0

### Configuration

[ansible@Ansible ansible]$ ansible-config dump --only-changed
[ansible@Ansible ansible]$

### OS / Environment

Rockylinux 9

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
