### ISSUE TITLE
Proxmox dynamic inventory compose options not working

### ISSUE THREAD

**Issue by binbashroot** [ansible-collections/community.proxmox#34]
### Summary

Unless I'm misunderstanding how the compose option works, I don't believe the option to be working.  I started out by trying to declare the path for the ansible_ssh_private_key_file but running playbooks using a dynamic inventory would never accept the variable.  Further testing showed that anything declared in the compose section do not appear to be passed to the host at all.

### Issue Type

Bug Report

### Component Name

community.general.proxmox

### Ansible Version

```console (paste below)
$ ansible --version

```
ansible [core 2.12.7]

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

```
community.general 5.6.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```
CALLBACKS_ENABLED
DEFAULT_GATHERING
DEFAULT_HOST_LIST
DEFAULT_ROLES_PATH
HOST_KEY_CHECKING

### OS / Environment

RHEL9 

### Steps to Reproduce

```yaml (paste below)

```
```
### my.proxmox.yml
plugin: community.general.proxmox
validate_certs: false
url: "https://{{ lookup('env','PROXMOX_HOST') }}:8006"
want_proxmox_nodes_ansible_host: false
want_facts: true
keyed_groups:
   - key: proxmox_tags_parsed
groups:
    ansible_servers: "'rhel9' in (proxmox_tags_parsed|list)"
compose:
    foo: "hello"
    bar: "world"


### playbook.yml
- hosts: ansible_servers
  gather_facts: True
  vars: 
         ansible_ssh_private_key_file: '~/.ssh/id_rsa'

  tasks: 
    - debug:
        var: foo

    - debug:
        var: bar



### command syntax
ansible-playbook -i dynamic.proxmox.yml foo.yml 

```

### Expected Results

PLAY [ansible_servers] *********************************************************

TASK [Gathering Facts] *********************************************************
Wednesday 14 September 2022  21:22:24 -0400 (0:00:00.014)       0:00:00.014 ***
ok: [ansible.example.com]

TASK [debug] *******************************************************************
Wednesday 14 September 2022  21:22:25 -0400 (0:00:01.209)       0:00:01.224 ***
ok: [ansible.example.com] => {
    "foo": "hello"
}

TASK [debug] *******************************************************************
Wednesday 14 September 2022  21:22:25 -0400 (0:00:00.052)       0:00:01.277 ***
ok: [ansible.example.com] => {
    "bar": "world"
}

PLAY RECAP *********************************************************************
ansible.example.com        : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Actual Results

```console (paste below)

```
PLAY [ansible_servers] *********************************************************

TASK [Gathering Facts] *********************************************************
Wednesday 14 September 2022  21:22:24 -0400 (0:00:00.014)       0:00:00.014 ***
ok: [ansible.example.com]

TASK [debug] *******************************************************************
Wednesday 14 September 2022  21:22:25 -0400 (0:00:01.209)       0:00:01.224 ***
ok: [ansible.example.com] => {
    "foo": "VARIABLE IS NOT DEFINED!"
}

TASK [debug] *******************************************************************
Wednesday 14 September 2022  21:22:25 -0400 (0:00:00.052)       0:00:01.277 ***
ok: [ansible.example.com] => {
    "bar": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
ansible.example.com        : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by brad-charboneau** [comment]
this works for static variables, but how do we for example parse the host ip into ansible_host compose variable? 

I tried the example in the docs, but it does not work.
```
 ansible_host: "proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')"
```

Any help would be great. Thanks in advance!

**Comment by binbashroot** [comment]
@brad-charboneau  Try using:
    ansible_host: proxmox_agent_interfaces[1].ip-addresses[0]|ansible.utils.ipaddr('address')

Not sure why this issue hasn't been closed.  It should be.

**Comment by brad-charboneau** [comment]
> [@brad-charboneau](https://github.com/brad-charboneau) Try using: ansible_host: proxmox_agent_interfaces[1].ip-addresses[0]|ansible.utils.ipaddr('address')
> 
> Not sure why this issue hasn't been closed. It should be.

did not work, its like its not parsing the inventory and only accepting static values

it works when i do static value
ansible_host: "'192.168.101.7'"
but not when i try any form of parsing pattern within the plugin config

```yaml
---
plugin: community.general.proxmox
url: https://REDACTED:8006
user: REDACTED@pve
token_id: REDACTED
token_secret: REDACTED
validate_certs: true
want_facts: true

#host_key: proxmox_net0.ip
#keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
#  - key: proxmox_tags_parsed
#    separator: ""
    # prefix: group
#groups:
#  servarr: "'arrs_server' in (proxmox_tags_parsed|list)"
#  plexservers: "'plex_server' in (proxmox_tags_parsed|list)"
#  ansibleservers: "'ansible_server' in (proxmox_tags_parsed|list)"
#  gameservers: "'game_server' in (proxmox_tags_parsed|list)"
compose:
  ansible_port: "22"
  ansible_user: "'root'"
  ansible_host: proxmox_agent_interfaces[1].ip-addresses[0]|ansible.utils.ipaddr('address')
  
# Note that this can easily give you wrong values as ansible_host. See further below for
# an example where this is set to `false` and where ansible_host is set with `compose`.
want_proxmox_nodes_ansible_host: false
```
