### ISSUE TITLE
proxmox_kvm: can't check if VM exists

### ISSUE THREAD

**Issue by Vanav** [ansible-collections/community.proxmox#39]
### Summary

I want to check if VM exists by its name (to workaround another issue ansible-collections/community.proxmox#23). But it fails if VM doesn't exist.

### Steps to Reproduce
```
- name: Check if VM exists
  proxmox_kvm:
    api_host: '{{ proxmox_api_host }}'
    api_user: '{{ proxmox_api_user }}'
    api_password: '{{ proxmox_api_password }}'
    node: pve
    name: fresh-ubuntu-22
    state: current
  delegate_to: localhost
```

### Actual Results
```
fatal: [fresh_ubuntu_22_node -> localhost]: FAILED! => 
    changed: false
    msg: VM with name = fresh-ubuntu-22 does not exist in cluster
```

### Expected Results
I expect to not get fatal error, but to get VM state or id.

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.1]
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
community.general 6.1.0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by PendaGTP** [comment]
@IamLunchbox

This issue can be closed.

```yml
- name: Retrieve information about specific VM by ID
  community.proxmox.proxmox_vm_info:
    type: qemu
    vmid: 100 # this vm doesnt exist
```

Returns:

```json
{ "changed": false, "proxmox_vms": [] }
```
