### ISSUE TITLE
Add a way to create proxmox VM based on backup / archive 

### ISSUE THREAD

**Issue by l00ptr** [ansible-collections/community.proxmox#42]
### Summary

Hi there,

It would be nice to add a way to create a VM based on backup / archive. The proxmox API allows this by using the archive param : https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu

When restoring / creating a VM, we should probably disable all param to customize the new one.

### Issue Type

Feature Idea

### Component Name

proxmox

### Additional Information

This is an example how i imagine to use this feature:

```yaml 
- name: Create a VM from archive (backup)
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: secret
    api_host: helldorado
    archive: backup-storage:backup/vm/140/2023-03-08T06:41:23Z
    name: spynal
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
