### ISSUE TITLE
[proxmox] Attempting to delete a running LXC container is not treated as failure

### ISSUE THREAD

**Issue by b-** [ansible-collections/community.proxmox#49]
### Summary

If I try to delete an LXC container that is presently running, the task appears to succeed. However, running with `-v` shows that it actually failed.

See here: https://github.com/ansible-collections/community.general/blob/be9dcd2c85f0fc940a67f3d13c6f9df897b273bb/plugins/modules/proxmox.py#L818

A number of the scenarios that this block goes through should probably call `fail_json()` rather than `exit_json()`.

I didn't want to just change it and issue a PR, because for all I know somebody might be relying on it to not emit a failure in this case? (see [relevant XKCD](https://xkcd.com/1172/))

### Issue Type

Bug Report

### Component Name

proxmox

### Ansible Version

```console (paste below)
bri@deb-dev:~/home-k0s$ ansible --version
ansible [core 2.15.4]
  config file = None
  configured module search path = ['/home/bri/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bri/home-k0s/.direnv/python-3.11/lib/python3.11/site-packages/ansible
  ansible collection location = /home/bri/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/bri/home-k0s/.direnv/python-3.11/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/bri/home-k0s/.direnv/python-3.11/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
bri@deb-dev:~/home-k0s$ ansible-galaxy collection list community.general

# /home/bri/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.5.0  

```

### Configuration

```console (paste below)
bri@deb-dev:~/home-k0s$ ansible-config dump --only-changed
CONFIG_FILE() = None
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = ['/home/bri/home-k0s/ansible/inventory']
```

### OS / Environment

Debian 12 in an LXC container running on a Proxmox server

### Steps to Reproduce

```yaml
---
- name: Create lxc container
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: "/tmp/venv/bin/python"
    pve_api_host: "my-pve-server.mydomain.com" # url to access the proxmox server
    pve_api_user: "root@pam" # if you didn't create any other accounts...
    pve_api_password: "p4ssw0rd" # don't actually put this in your playbook
    pve_node: "macpro" # it may be different in a cluster
    vm_ostemplate_storage: "local"
    vm_disk_storage: "local-lvm"
    vm_ostemplate: "debian-12-standard_12.0-1_amd64.tar.zst"
    vm_id: "123456"
    vm_memory: "256"
    vm_swap: "256"

  tasks:
    - name: Download proxmox appliance container template
      run_once: true
      community.general.proxmox_template:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ pve_node }}"
        storage: "{{ vm_ostemplate_storage }}"
        content_type: "vztmpl"
        template: "{{ vm_ostemplate }}"

    - name: Create a new container
      community.general.proxmox:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ pve_node }}"
        storage: "{{ vm_disk_storage }}"
        description: "{{ inventory_hostname }}"
        hostname: "{{ inventory_hostname }}"
        password: "234567"
        ostemplate: "{{ vm_ostemplate_storage }}:vztmpl/{{ vm_ostemplate }}"
        vmid: "{{ vm_id }}"
        memory: "{{ vm_memory }}"
        swap: "{{ vm_swap }}"
#        netif:
#          '{"net0":"name=eth0,ip={{ vm_net0_cidr }},bridge={{ vm_net0_bridge }},gw={{ vm_net0_gateway }}" }'
        state: "present"

    - name: Start lxc container
      community.general.proxmox:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        state: 'started'

    - name: Destroy a container
      register: "destroy_vm_result"
      community.general.proxmox:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ pve_node }}"
        vmid: "{{ vm_id }}"
        state: 'absent'

    - name: Output
      ansible.builtin.debug:
        var: "destroy_vm_result"
```

### Expected Results

I expect the `Destroy a container` task to **skip** or **fail**, due to being unable to remove a running container.

### Actual Results

```console (paste below)
(venv) bri@deb-dev:~/a$ ansible-playbook -i i.yaml /home/bri/home-k0s/ansible/playbooks/create-basic-lxc.yaml

PLAY [Create lxc container] **************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************
ok: [lxc1]

TASK [Download proxmox appliance container template] *************************************************************************************************************************************
ok: [lxc1]

TASK [Create a new container] ************************************************************************************************************************************************************
changed: [lxc1]

TASK [Start lxc container] ***************************************************************************************************************************************************************
changed: [lxc1]

TASK [Destroy a container] ***************************************************************************************************************************************************************
ok: [lxc1]

TASK [Output] ****************************************************************************************************************************************************************************
ok: [lxc1] => {
    "destroy_vm_result": {
        "changed": false,
        "failed": false,
        "msg": "VM 123456 is running. Stop it before deletion.",
        "vmid": 123456
    }
}

PLAY RECAP *******************************************************************************************************************************************************************************
lxc1                       : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
