### ISSUE TITLE
community.general.proxmox_kvm won't adjust cpu/memory/ballooning with cloned VMs

### ISSUE THREAD

**Issue by PC-Admin** [ansible-collections/community.proxmox#50]
### Summary

The community.general.proxmox_kvm module doesn't allow you to set cores/memory/balloon/shares settings when cloning a VM.

It copies these values from the clone and ignores values defined in the Ansible task. As a workaround I ended up using the Proxmox API, but it would be cool if this module could handle it instead.

Here's the module for reference: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_kvm_module.html

### Issue Type

Bug Report

### Component Name

community.general.proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.15.4]
  config file = /home/pcadmin/MyVault/PSP_Repos/provision-servers/ansible.cfg
  configured module search path = ['/home/pcadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/pcadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/pcadmin/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 7.3.0 
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22.04 for the Ansible controller
Proxmox 8.0 cluster

### Steps to Reproduce

1) Get a Proxmox 8 server/cluster setup.

2) Create a VM template for whatever OS you fancy.

3) Attempt to clone it while specifying cores, memory, balloon/shares using an Ansible task that's similar to this one:
```
- name: "Create a full clone of the template for each host (sequentially)"
  delegate_to: localhost
  community.general.proxmox_kvm:
    api_host: "{{ hostvars[item].proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    node: "{{ hostvars[item].proxmox_node }}"
    clone: "{{ hostvars[item].proxmox_template }}"
    storage: "{{ hostvars[item].proxmox_storage }}"
    cores: "{{ hostvars[item].proxmox_kvm_cores | int }}"
    memory: "{{ hostvars[item].proxmox_kvm_memory | int }}"
    balloon: "{{ hostvars[item].proxmox_kvm_balloon | int }}"
    shares: "{{ hostvars[item].proxmox_kvm_shares | int }}"
    full: true
    state: present
    timeout: 300
  register: new_clone_info
  when: hostvars[item].spawn_on_proxmox | bool
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    pause: 1
  run_once: true
```

### Expected Results

I expect that the values defined here would actually be applied to that new host:
```
    cores: "{{ hostvars[item].proxmox_kvm_cores | int }}"
    memory: "{{ hostvars[item].proxmox_kvm_memory | int }}"
    balloon: "{{ hostvars[item].proxmox_kvm_balloon | int }}"
    shares: "{{ hostvars[item].proxmox_kvm_shares | int }}"
```

### Actual Results

But even when running this task repeatedly it only copies these values from the VM template.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
