### ISSUE TITLE
proxmox_kvm - Unable to import Ubuntu cloud image in .img format.

### ISSUE THREAD

**Issue by BladeWDR** [ansible-collections/community.proxmox#53]
### Summary

The proxmox_kvm module doesn't appear to work with the cloud images provided by Ubuntu. The same play works with a qcow2 file provided by Debian,

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
ansible [core 2.15.1]
  config file = /home/scott/git/doting_calamity/ansible.cfg
  configured module search path = ['/home/scott/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/scott/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/scott/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/scott/ansible/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/home/scott/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
# /home/scott/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 8.2.0

# /home/scott/ansible/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.1.0
```

### Configuration

```console (paste below)
CONFIG_FILE() = /home/scott/git/doting_calamity/ansible.cfg
DEFAULT_HOST_LIST(/home/scott/git/doting_calamity/ansible.cfg) = ['/home/scott/git/doting_calamity/hosts']
DEFAULT_PRIVATE_KEY_FILE(/home/scott/git/doting_calamity/ansible.cfg) = /home/scott/.ssh/ansible
DEFAULT_REMOTE_USER(/home/scott/git/doting_calamity/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/scott/git/doting_calamity/ansible.cfg) = ['/home/scott/git/doting_calamity/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/scott/git/doting_calamity/ansible.cfg) = /home/scott/git/doting_calamity/vaultpass
HOST_KEY_CHECKING(/home/scott/git/doting_calamity/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/scott/git/doting_calamity/ansible.cfg) = False
```

### OS / Environment

Proxmox 8.1.3

### Steps to Reproduce

The proxmox_kvm module doesn't appear to work with the cloud images provided by Ubuntu. The same play works with a qcow2 file provided by Debian, but if you use any of the .img files provided [here](https://cloud-images.ubuntu.com/jammy/current/) it gives this error:

`"msg": "creation of qemu VM testvm with vmid 133 failed with exception=500 Internal Server Error: unable to parse volume filename 'jammy-server-cloudimg-amd64-disk-kvm.img'", "vmid": 133}`

Here is the play in question:

```
- name: "Create the VMs on Proxmox node 1."
  community.general.proxmox_kvm:
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    api_host: '{{ gv_proxmox_api_host }}'
    node: '{{ item.node }}'
    name: '{{ item.name }}'
    vmid: '{{ item.vmid }}'
    vga: serial0
    net: '{"net0":"virtio,bridge={{ gv_proxmox_linux_bridge }},firewall=1"}'
    serial: '{"serial0":"socket"}'
    scsihw: virtio-scsi-single
    scsi:
      scsi0: '{{ item.drive_storage }}:0,import-from={{ gv_proxmox_image_storage }}:0/{{ item.image_file }},format={{ item.drive_format }},iothread=1'
    ide:
      ide2: '{{ item.drive_storage }}:cloudinit'
    ostype: 'l26'
    onboot: 'no'
    cpu: 'host'
    cores: '{{ item.cores }}'
    sockets: 1
    memory: '{{ item.memory }}'
    balloon: 0
    boot: order=scsi0
    ipconfig:
      ipconfig0: 'ip=dhcp'
    cicustom: 'user={{ gv_proxmox_snippets_storage }}:snippets/{{ item.vmid }}-user.yml'
    agent: 'enabled=1'
    timeout: 700
  loop: '{{ computers }}'
  when: 'item.state == "new"'
```

I have tried hard coding the variables for scsi0 just to make sure it wasn't an issue with how the variables were being interpreted, but had the same issue.

I'm not sure if this is an issue with the collection or something internal to proxmoxer.

### Expected Results

I expected the volume to be imported like the qcow2 is.

Running `qm import VMID` with the same image file works.

### Actual Results

```console (paste below)
The full traceback is:
  File "/tmp/ansible_community.general.proxmox_kvm_payload_lh72o60x/ansible_community.general.proxmox_kvm_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_kvm.py", line 1432, in main
  File "/tmp/ansible_community.general.proxmox_kvm_payload_lh72o60x/ansible_community.general.proxmox_kvm_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_kvm.py", line 1132, in create_vm
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 135, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 126, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 105, in _request
    raise ResourceException(
failed: [sb-proxmox.bladewdr.xyz] (item={'name': 'testvm', 'vmid': '133', 'node': 'SB-PROXMOX', 'image_file': 'jammy-server-cloudimg-amd64-disk-kvm.img', 'cpu_type': 'x86-64-v2-AES', 'cores': 2, 'drive_storage': 'fast', 'drive_format': 'raw', 'disk_size': '32GB', 'memory': 2048, 'ipv4mode': 'static', 'ipv4_address': '10.13.37.222/24', 'ipv4_gateway': '10.13.37.1', 'state': 'new'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "acpi": null,
            "agent": "enabled=1",
            "api_host": "sb-proxmox.bladewdr.xyz",
            "api_password": null,
            "api_token_id": "terraform",
            "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "terraform@pam",
            "archive": null,
            "args": null,
            "autostart": null,
            "balloon": 0,
            "bios": null,
            "boot": "order=scsi0",
            "bootdisk": null,
            "cicustom": "user=local:snippets/133-user.yml",
            "cipassword": null,
            "citype": null,
            "ciuser": null,
            "clone": null,
            "cores": 2,
            "cpu": "host",
            "cpulimit": null,
            "cpuunits": null,
            "delete": null,
            "description": null,
            "digest": null,
            "efidisk0": null,
            "force": null,
            "format": null,
            "freeze": null,
            "full": true,
            "hookscript": null,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": {
                "ide2": "fast:cloudinit"
            },
            "ipconfig": {
                "ipconfig0": "ip=dhcp"
            },
            "keyboard": null,
            "kvm": null,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 2048,
            "migrate": false,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "testvm",
            "net": {
                "net0": "virtio,bridge=vmbr0,firewall=1"
            },
            "newid": null,
            "node": "SB-PROXMOX",
            "numa": null,
            "numa_enabled": null,
            "onboot": false,
            "ostype": "l26",
            "parallel": null,
            "pool": null,
            "protection": null,
            "proxmox_default_behavior": "no_defaults",
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": {
                "scsi0": "fast:0,import-from=local:0/jammy-server-cloudimg-amd64-disk-kvm.img,format=raw,iothread=1"
            },
            "scsihw": "virtio-scsi-single",
            "serial": {
                "serial0": "socket"
            },
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "sshkeys": null,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": null,
            "tablet": null,
            "tags": null,
            "target": null,
            "tdf": null,
            "template": null,
            "timeout": 700,
            "tpmstate0": null,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "serial0",
            "virtio": null,
            "vmid": 133,
            "watchdog": null
        }
    },
    "item": {
        "cores": 2,
        "cpu_type": "x86-64-v2-AES",
        "disk_size": "32GB",
        "drive_format": "raw",
        "drive_storage": "fast",
        "image_file": "jammy-server-cloudimg-amd64-disk-kvm.img",
        "ipv4_address": "10.13.37.222/24",
        "ipv4_gateway": "10.13.37.1",
        "ipv4mode": "static",
        "memory": 2048,
        "name": "testvm",
        "node": "SB-PROXMOX",
        "state": "new",
        "vmid": "133"
    },
    "msg": "creation of qemu VM testvm with vmid 133 failed with exception=500 Internal Server Error: unable to parse volume filename 'jammy-server-cloudimg-amd64-disk-kvm.img'",
    "vmid": 133
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
