### ISSUE TITLE
proxmox_kvm: Set timeout on Proxmoxer connections

### ISSUE THREAD

**Issue by aph3rson** [ansible-collections/community.proxmox#55]
### Summary

This is related to [this PVE Forums thread](https://forum.proxmox.com/threads/intermittent-network-loss-from-vm-node.142042/). I'm having issues with a slow-to-respond PVE API, and the current timeout is set to the default of 5 seconds. I'd like to be able to increase that.

### Issue Type

Feature Idea

### Component Name

proxmox_kvm

### Additional Information

Here's an example of what this might look like in a template:

```yaml
      community.general.proxmox_kvm:
        api_host: "{{ hostvars.pve.ansible_host }}"
        api_user: "{{ hostvars.pve.ansible_user }}@pam"
        api_password: "{{ hostvars.pve.ansible_ssh_pass }}"
        api_timeout: 10  # <--- new
        node: pve-1
        vmid: "{{ item.value.vmid }}"
        state: absent
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
