### ISSUE TITLE
proxmox: update of LXC Containers does not work (Mounts/Memory/etc.)

### ISSUE THREAD

**Issue by Exzellius** [ansible-collections/community.proxmox#69]
### Summary

When trying ot update a running LXC on proxmox, I get <OK> return for ansible and nothing about the configuration is changed, even tho I clearly indicate so in the playbook.

### Issue Type

Bug Report

### Component Name

community.general.proxmox

### Ansible Version

```console (paste below)
$ ansible --version
ansible:/ansible # ansible --version
ansible [core 2.16.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.10 (main, Sep 18 2024, 22:14:32) [GCC] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
ansible:/ansible #
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
ansible:/ansible # ansible-galaxy collection list community.general

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 9.5.0

# /usr/lib/python3.11/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.5.0
ansible:/ansible #
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ansible:/ansible # ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/ansible/inventory.yaml']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /ansible/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /ansible/vault_passwd.txt
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
PAGER(env: PAGER) = less
ansible:/ansible #
```

### OS / Environment

OpenSuse Leap 15.6

### Steps to Reproduce

```yaml (paste below)
- name: Proxmox Create Container
  hosts: nextcloud
  gather_facts: false
  connection: local

  module_defaults:
    group/community.general.proxmox:
      api_host: pve01.exzellius.local
      api_user: ansible@pve
      api_token_id: ansible_token
      api_token_secret: "{{ pve_api_token_password }}"
      validate_certs: false

  tasks:
    - name: Update Container-Configs
      community.general.proxmox:
        state: started
        update: true
        cores: 4
        memory: 4096
        swap: 512
        mounts:
          mp0: "lvm:155,mp=/nextcloud_data,backup=1"
        vmid: 204
```

### Expected Results

New config parameters should be applied and the status of the task should be changed.

### Actual Results

```console (paste below)
ansible:/ansible # ansible-playbook pve_test.yaml -vvvv
ansible-playbook [core 2.16.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.10 (main, Sep 18 2024, 22:14:32) [GCC] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from
host_list declined parsing /ansible/inventory.yaml as it did not pass its verify_file() method
script declined parsing /ansible/inventory.yaml as it did not pass its verify_file() method
Parsed /ansible/inventory.yaml inventory source with yaml plugin
Loading collection community.general from /root/.ansible/collections/ansible_collections/community/general
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.11/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: pve_test.yaml **************************************************************************************************************************************
Positional arguments: pve_test.yaml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/ansible/inventory.yaml',)
forks: 5
1 plays in pve_test.yaml

PLAY [Proxmox Create Container] ******************************************************************************************************************************
Trying secret FileVaultSecret(filename='/ansible/vault_passwd.txt') for vault_id=default

TASK [Update Container-Configs] ******************************************************************************************************************************
task path: /ansible/pve_test.yaml:15
<{{inventory_hostname}}.{{ dns_domain }}> ESTABLISH LOCAL CONNECTION FOR USER: root
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c 'echo ~root && sleep 0'
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956 `" && echo ansible-tmp-1729713251.1884532-845233-140897991318956="` echo /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956 `" ) && sleep 0'
<nextcloud> Attempting python interpreter discovery
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.12'"'"'; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c '/usr/bin/python3.11 && sleep 0'
<nextcloud> Python interpreter discovery fallback (unsupported Linux distribution: opensuse-leap)
Using module file /root/.ansible/collections/ansible_collections/community/general/plugins/modules/proxmox.py
<{{inventory_hostname}}.{{ dns_domain }}> PUT /root/.ansible/tmp/ansible-local-845230tufr97yi/tmpomylde6y TO /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956/AnsiballZ_proxmox.py
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956/ /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956/AnsiballZ_proxmox.py && sleep 0'
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c '/usr/bin/python3.11 /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956/AnsiballZ_proxmox.py && sleep 0'
<{{inventory_hostname}}.{{ dns_domain }}> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1729713251.1884532-845233-140897991318956/ > /dev/null 2>&1 && sleep 0'
ok: [nextcloud] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.11"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "api_host": "pve01.exzellius.local",
            "api_password": null,
            "api_port": null,
            "api_token_id": "ansible_token",
            "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "ansible@pve",
            "clone": null,
            "clone_type": "opportunistic",
            "cores": 4,
            "cpus": null,
            "cpuunits": null,
            "description": null,
            "disk": null,
            "disk_volume": null,
            "features": null,
            "force": false,
            "hookscript": null,
            "hostname": null,
            "ip_address": null,
            "memory": 4096,
            "mount_volumes": null,
            "mounts": {
                "mp0": "lvm:155,mp=/nextcloud_data,backup=1"
            },
            "nameserver": null,
            "netif": null,
            "node": null,
            "onboot": null,
            "ostemplate": null,
            "ostype": "auto",
            "password": null,
            "pool": null,
            "pubkey": null,
            "purge": false,
            "searchdomain": null,
            "startup": null,
            "state": "started",
            "storage": "local",
            "swap": 512,
            "tags": null,
            "timeout": 30,
            "timezone": null,
            "unprivileged": true,
            "update": true,
            "validate_certs": false,
            "vmid": 204
        }
    },
    "msg": "VM 204 is already running",
    "vmid": 204
}

PLAY RECAP ***************************************************************************************************************************************************
nextcloud                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

ansible:/ansible #
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by CGHoussem** [comment]
I have also issues with updating the LXC containers in my cluster.

I am using ansible version 2.20.3 and the latest proxmox community collection (version 1.5.0).

```bash
> ansible --version
ansible [core 2.20.3]
  config file = None
  configured module search path = ['/home/pxhoussem/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.14/site-packages/ansible
  ansible collection location = /home/pxhoussem/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.14.3 (main, Feb 13 2026, 15:31:44) [GCC 15.2.1 20260209] (/usr/bin/python)
  jinja version = 3.1.6
  pyyaml version = 6.0.3 (with libyaml v0.2.5)

> ansible-galaxy collection list community.proxmox

# /home/pxhoussem/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.proxmox 1.5.0
```

Here is my playbook tasks:
```yaml
    - name: Create LXC container for {{ inventory_hostname }}
      community.proxmox.proxmox:
        vmid: "{{ item.id }}"
        node: "{{ inventory_hostname }}"
        hostname: "{{ item.name }}"
        ostemplate: "{{ 'local:vztmpl/' + item.template | default(default_lxc_ostemplate) }}"
        # memory: "{{ item.memory }}"
        # swap: "{{ item.swap }}"
        # cores: "{{ item.cores }}"
        # features: "{{ item.features | default(default_lxc_features) }}"
        # startup: "{{ item.startup | default(omit) }}"
        # disk_volume:
        #   storage: "{{ item.storage | default(default_lxc_storage) }}"
        #   size: "{{ item.disk_volume_size | default(default_lxc_disk_volume_size) }}"
        # mounts: "{{ item.mount | default(omit) }}"
        # mount_volumes: "{{ item.mount_volumes | default(omit) }}"
        netif: "{{ item.netif | default(omit) }}"
        # pubkey: "{{ bigpc_ssh_pubkey | default(omit) }}"
        # unprivileged: "{{ item.unprivileged | default(true) }}"
        # onboot: "{{ item.onboot | default(true) }}"
        state: present
      loop: "{{ node_containers | selectattr('node', 'equalto', inventory_hostname) | map(attribute='containers') | first }}"
      loop_control:
        loop_var: item
      register: lxc_create_results
      failed_when:
        - lxc_create_results.failed
        - "'already exists' not in (lxc_create_results.msg | default(''))"
      delegate_to: localhost

    - name: Update LXC container for {{ inventory_hostname }}
      community.proxmox.proxmox:
        vmid: "{{ item.id }}"
        node: "{{ inventory_hostname }}"
        hostname: "{{ item.name }}"
        ostemplate: "{{ 'local:vztmpl/' + item.template | default(default_lxc_ostemplate) }}"
        # memory: "{{ item.memory }}"
        # swap: "{{ item.swap }}"
        # cores: "{{ item.cores }}"
        # features: "{{ item.features | default(default_lxc_features) }}"
        # startup: "{{ item.startup | default(omit) }}"
        # disk_volume:
        #   storage: "{{ item.storage | default(default_lxc_storage) }}"
        #   size: "{{ item.disk_volume_size | default(default_lxc_disk_volume_size) }}"
        # mounts: "{{ item.mount | default(omit) }}"
        # mount_volumes: "{{ item.mount_volumes | default(omit) }}"
        netif: "{{ item.netif | default(omit) }}"
        # pubkey: "{{ bigpc_ssh_pubkey | default(omit) }}"
        # unprivileged: "{{ item.unprivileged | default(true) }}"
        # onboot: "{{ item.onboot | default(true) }}"
        state: present
        update: true
      loop: "{{ node_containers | selectattr('node', 'equalto', inventory_hostname) | map(attribute='containers') | first }}"
      loop_control:
        loop_var: item
      delegate_to: localhost
```

The creation / update of an LXC container was on a single task but I kept getting the same error, so I divided and commented some attributes thinking to be less error-prone, but nope.. I still have an error.

The error in question is the following:

`[ERROR]: Task failed: Module failed: An error occurred: 500 Internal Server Error: CT 301 already exists on node 'proxmox-node03'`

```bash
TASK [Create LXC container for proxmox-node03] ************************************************************************************************************************************************************************************************
ok: [proxmox-node03 -> localhost] => (item={'name': 'monitoring', 'id': 301, 'memory': 4096, 'swap': 2048, 'cores': 2, 'netif': {'net0': 'name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:2E:C8:42,ip=192.168.1.231/24,type=veth'}, 'disk_volume_size': 16, 'startup': ['order=8']}) => {"ansible_loop_var": "item", "changed": false, "failed_when_result": false, "failed_when_suppressed_exception": "(traceback unavailable)", "item": {"cores": 2, "disk_volume_size": 16, "id": 301, "memory": 4096, "name": "monitoring", "netif": {"net0": "name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:2E:C8:42,ip=192.168.1.231/24,type=veth"}, "startup": ["order=8"], "swap": 2048}, "msg": "An error occurred: 500 Internal Server Error: CT 301 already exists on node 'proxmox-node03'"}
ok: [proxmox-node03 -> localhost] => (item={'name': 'gh-runner', 'id': 302, 'memory': 1024, 'swap': 512, 'cores': 1, 'netif': {'net0': 'name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:C5:24:F2,ip=192.168.1.233/24,type=veth'}, 'disk_volume_size': 8, 'template': 'ubuntu-24.04-standard_24.04-2_amd64.tar.zst'}) => {"ansible_loop_var": "item", "changed": false, "failed_when_result": false, "failed_when_suppressed_exception": "(traceback unavailable)", "item": {"cores": 1, "disk_volume_size": 8, "id": 302, "memory": 1024, "name": "gh-runner", "netif": {"net0": "name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:C5:24:F2,ip=192.168.1.233/24,type=veth"}, "swap": 512, "template": "ubuntu-24.04-standard_24.04-2_amd64.tar.zst"}, "msg": "An error occurred: 500 Internal Server Error: CT 302 already exists on node 'proxmox-node03'"}

TASK [Update LXC container for proxmox-node03] ************************************************************************************************************************************************************************************************
[ERROR]: Task failed: Module failed: An error occurred: 500 Internal Server Error: CT 301 already exists on node 'proxmox-node03'
Origin: /home/pxhoussem/Documents/Projects/CGHoussem/px-homelab/ansible/deploy-lxc-containers.yml:82:7

80       delegate_to: localhost
81
82     - name: Update LXC container for {{ inventory_hostname }}
         ^ column 7

failed: [proxmox-node03 -> localhost] (item={'name': 'monitoring', 'id': 301, 'memory': 4096, 'swap': 2048, 'cores': 2, 'netif': {'net0': 'name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:2E:C8:42,ip=192.168.1.231/24,type=veth'}, 'disk_volume_size': 16, 'startup': ['order=8']}) => {"ansible_loop_var": "item", "changed": false, "item": {"cores": 2, "disk_volume_size": 16, "id": 301, "memory": 4096, "name": "monitoring", "netif": {"net0": "name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:2E:C8:42,ip=192.168.1.231/24,type=veth"}, "startup": ["order=8"], "swap": 2048}, "msg": "An error occurred: 500 Internal Server Error: CT 301 already exists on node 'proxmox-node03'"}
[ERROR]: Task failed: Module failed: An error occurred: 500 Internal Server Error: CT 302 already exists on node 'proxmox-node03'
Origin: /home/pxhoussem/Documents/Projects/CGHoussem/px-homelab/ansible/deploy-lxc-containers.yml:82:7

80       delegate_to: localhost
81
82     - name: Update LXC container for {{ inventory_hostname }}
         ^ column 7

failed: [proxmox-node03 -> localhost] (item={'name': 'gh-runner', 'id': 302, 'memory': 1024, 'swap': 512, 'cores': 1, 'netif': {'net0': 'name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:C5:24:F2,ip=192.168.1.233/24,type=veth'}, 'disk_volume_size': 8, 'template': 'ubuntu-24.04-standard_24.04-2_amd64.tar.zst'}) => {"ansible_loop_var": "item", "changed": false, "item": {"cores": 1, "disk_volume_size": 8, "id": 302, "memory": 1024, "name": "gh-runner", "netif": {"net0": "name=eth0,bridge=vmbr0,gw=192.168.1.254,hwaddr=BC:24:11:C5:24:F2,ip=192.168.1.233/24,type=veth"}, "swap": 512, "template": "ubuntu-24.04-standard_24.04-2_amd64.tar.zst"}, "msg": "An error occurred: 500 Internal Server Error: CT 302 already exists on node 'proxmox-node03'"}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
proxmox-node03             : ok=3    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
```

I've played with the `state` attrribute value, even though the documentation clearly says that it needs to be **present,** but still same problem.

If anyone is updating his/her LXC Container I would love to know how.
