### ISSUE TITLE
proxmox_template upload timeout=5s can't be changed and too short

### ISSUE THREAD

**Issue by elelayan** [ansible-collections/community.proxmox#71]
### Summary

When I upload an iso to my cluster it takes ~20s.

See  is the upload task.

Here is the error I get:

````
msg: 'Uploading template files/isos/myhost.iso failed with error: (''Connection aborted.'', TimeoutError(''The write operation timed out''))'
````

I think the timeout needs to be specified when creating the ProxmoxAPI object in [proxmox.py](https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/proxmox.py#L109).

At least it works for me when I change to `return ProxmoxAPI(api_host, verify_ssl=validate_certs, timeout=42, **auth_args)`.
And I see the effect when logging the timeout value in `ProxmoxHttpSession` in `proxmoxer/backend/https.py` line 232.

### Issue Type

Bug Report

### Component Name

proxmox_template

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.14.17]
  config file = /home/xxx/.../ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.tox/py3-ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/xxxxx/collections-dependencies:/home/xxxxx/collections
  executable location = /home/xxxx/.tox/py3-ansible/bin/ansible
  python version = 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0] (/home/xxxxx/.tox/py3-ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/xxxx/collections-dependencies/ansible_collections
Collection        Version
----------------- -------
community.general 8.6.7  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Debian 12

### Steps to Reproduce

```yaml (paste below)
    - name: Upload CDROM
      community.general.proxmox_template: "{{ pve_api | combine(task_params) }}"
      delegate_to: localhost
      vars:
        task_params:
          content_type: iso
          src: "files/isos/{{ inventory_hostname }}.iso"
          storage: "{{ pve_iso_storage }}"
          force: true
```

### Expected Results

I expected the upload to succeed.

### Actual Results

```console (paste below)
msg: 'Uploading template files/isos/myhost.iso failed with error: (''Connection aborted.'', TimeoutError(''The write operation timed out''))'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Miguel-Rodrigues** [comment]
I also have the same exact issue.
I tried to set both 'timeout: 600' and ANSIBLE_TIMEOUT=600, but still fails after 10 seconds.
The code bellow tries each node until it completes the task once or fails.

Here is the playbook:
<details>
  <summary>playbook.yml</summary>

  ```yml
  - name: Stage 1 - Prepare
    gather_facts: no
    hosts: localhost
    tasks:
      - name: Get artifact location
        set_fact:
          artifact: "{{ lookup('pipe', 'ls -t ../../{{ ostemplate }} | head -n1') }}"
        when: artifact is not defined
  
  - name: Stage 2 - Publish archive
    gather_facts: no
    hosts: all
    serial: 1
    vars:
      ansible_python_interpreter: "/tmp/ansible-venv/bin/python3"
    tasks:
      - delegate_to: localhost
        block:
          - name: Upload new template
            community.general.proxmox_template:
              node: "{{ inventory_hostname }}"
              api_host: "{{ ansible_host }}"
              api_user: "{{ api_user }}"
              api_token_id: "{{ api_token_id }}"
              api_token_secret: "{{ api_token_secret }}"
              storage: "{{ storage }}"
              content_type: "{{ content_type }}"
              src: "{{ hostvars['localhost'].artifact }}"
              timeout: 600
              force: true
            register: report
        rescue:
          - debug: msg="[WARNING] Publish failed for {{ inventory_hostname }}, trying next host."
        always:
          - set_fact:
              last_report: "{{ report }}"
            delegate_to: localhost
            delegate_facts: true
          - meta: end_play
            when: report is succeeded
  
  - name: Check report
    gather_facts: no
    hosts: localhost
    tasks:
      - meta: end_play
        when: last_report is succeeded
      - fail:
          msg: "[ERROR] Could not complete the task: {{ last_report }}"
  ```
</details>

Here is the output:
<details>
  <summary>output</summary>

  ```log
   __________________________
  < PLAY [Stage 1 - Prepare] >
   --------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
   ______________________________
  < TASK [Get artifact location] >
   ------------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [localhost]
   __________________________________
  < PLAY [Stage 2 - Publish archive] >
   ----------------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
   ____________________________
  < TASK [Upload new template] >
   ----------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  fatal: [mox-node01 -> localhost]: FAILED! => {"changed": false, "msg": "uploading/downloading of template pve-yugabyte_2024.2.4.0.tar.gz failed with exception: ('Connection aborted.', TimeoutError('The write operation timed out'))"}
   ________________
  < TASK [RESCUE!] >
   ----------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node01 -> localhost] => {
      "msg": "[WARNING] Publish failed for mox-node01, trying next host."
  }
   ____________________
  < TASK [Save Report] >
   --------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node01 -> localhost]
   ___________________________
  < TASK [Has completed yet?] >
   ---------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  skipping: [mox-node01]
   __________________________________
  < PLAY [Stage 2 - Publish archive] >
   ----------------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
   ____________________________
  < TASK [Upload new template] >
   ----------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  fatal: [mox-node02 -> localhost]: FAILED! => {"changed": false, "msg": "uploading/downloading of template pve-yugabyte_2024.2.4.0.tar.gz failed with exception: ('Connection aborted.', TimeoutError('The write operation timed out'))"}
   ________________
  < TASK [RESCUE!] >
   ----------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node02 -> localhost] => {
      "msg": "[WARNING] Publish failed for mox-node02, trying next host."
  }
   ____________________
  < TASK [Save Report] >
   --------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node02 -> localhost]
   ___________________________
  < TASK [Has completed yet?] >
   ---------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  skipping: [mox-node02]
   __________________________________
  < PLAY [Stage 2 - Publish archive] >
   ----------------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
   ____________________________
  < TASK [Upload new template] >
   ----------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  fatal: [mox-node03 -> localhost]: FAILED! => {"changed": false, "msg": "uploading/downloading of template pve-yugabyte_2024.2.4.0.tar.gz failed with exception: ('Connection aborted.', TimeoutError('The write operation timed out'))"}
   ________________
  < TASK [RESCUE!] >
   ----------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node03 -> localhost] => {
      "msg": "[WARNING] Publish failed for mox-node03, trying next host."
  }
   ____________________
  < TASK [Save Report] >
   --------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  ok: [mox-node03 -> localhost]
   ___________________________
  < TASK [Has completed yet?] >
   ---------------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  skipping: [mox-node03]
   _____________________
  < PLAY [Check report] >
   ---------------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
   _____________
  < TASK [meta] >
   -------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  skipping: [localhost]
   _____________
  < TASK [fail] >
   -------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  fatal: [localhost]: FAILED! => {"changed": false, "msg": "[ERROR] Could not complete the task: {'failed': True, 'msg': \"uploading/downloading of template pve-yugabyte_2024.2.4.0.tar.gz failed with exception: ('Connection aborted.', TimeoutError('The write operation timed out'))\", 'changed': False}"}
   ____________
  < PLAY RECAP >
   ------------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  
  localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
  mox-node01                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0   
  mox-node02                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0   
  mox-node03                 : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0   
  ```
</details>

Here is the traceback of one of the errors:

<details>
  <summary>traceback</summary>
  
  ```
  The full traceback is:
    File "/tmp/ansible_community.general.proxmox_template_payload_jueynner/ansible_community.general.proxmox_template_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_template.py", line 227, in main
    File "/tmp/ansible_community.general.proxmox_template_payload_jueynner/ansible_community.general.proxmox_template_payload.zip/ansible_collections/community/general/plugins/modules/proxmox_template.py", line 152, in upload_template
    File "/tmp/ansible-venv/lib/python3.11/site-packages/proxmoxer/core.py", line 170, in post
      return self(args)._request("POST", data=data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/ansible-venv/lib/python3.11/site-packages/proxmoxer/core.py", line 142, in _request
      resp = self._store["session"].request(method, url, data=data, params=params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/ansible-venv/lib/python3.11/site-packages/proxmoxer/backends/https.py", line 235, in request
      return super().request(
             ^^^^^^^^^^^^^^^^
    File "/tmp/ansible-venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
      resp = self.send(prep, **send_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/ansible-venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
      r = adapter.send(request, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/ansible-venv/lib/python3.11/site-packages/requests/adapters.py", line 682, in send
      raise ConnectionError(err, request=request)
  fatal: [mox-node01 -> localhost]: FAILED! => {
      "changed": false,
      "invocation": {
          "module_args": {
              "api_host": "---------",
              "api_password": "---------",
              "api_token_id": "---------",
              "api_token_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
              "api_user":  "---------",
              "content_type": "vztmpl",
              "force": true,
              "node": "mox-node01",
              "src": "../../pve-yugabyte_2024.2.4.0.tar.gz",
              "state": "present",
              "storage": "mox-storage",
              "template": null,
              "timeout": 600,
              "validate_certs": false
          }
      },
      "msg": "uploading/downloading of template pve-yugabyte_2024.2.4.0.tar.gz failed with exception: ('Connection aborted.', TimeoutError('The write operation timed out'))"
  }
  ```
</details>
