### ISSUE TITLE
proxmox: seems like you cannot create a linked lxc clone, because if storage is omited or empty, it is defaulted to "local"

### ISSUE THREAD

**Issue by tolland** [ansible-collections/community.proxmox#74]
### Summary

When trying to use the `community.general.proxmox` module to create a linked clone of a template host, the code is checking that the value of the `storage` param is None, otherwise it it defaulting back to making a full copy of the disks. However if the param is actually set to none or not provided, the default value of the param is applied, and it is set to "local", hence vm is not link-cloned, but full cloned instead.

#### Background

If you try and created a linked clone with proxmox module, it always creates a full clone:

```
    - name: Create new container
      community.general.proxmox:
        <<: *_pve_config
        hostname: some-host-name
        pubkey: "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"
        clone: 118
        clone_type: linked
        timeout: 120
        # storage: "{{ omit }}" # <---- if this is omitted, or set to "" it is defaulted to "local"
        # storage: ""
        # storage: null
```

This is due to this code checking that storage is not None:
https://github.com/ansible-collections/community.general/blob/bb12db3c58ba44471ad5254952c2271b4bf7dde0/plugins/modules/proxmox.py#L891
```python
            if self.module.params['storage'] is not None and clone_is_template:
                # Cloning a template, so create a full copy instead of a linked copy
                create_full_copy = True
```
However if no param is actually provided, or the key is omitted or "", the default for the param is to set it to "local":
https://github.com/ansible-collections/community.general/blob/bb12db3c58ba44471ad5254952c2271b4bf7dde0/plugins/modules/proxmox.py#L1049

```
        storage=dict(default='local'),
```

I tried several variations of trying to unset the key, but it either throws an error:
```
  msg: 'argument ''storage'' is of type <class ''NoneType''> and we were unable to convert to str: ''None'' is not a string and conversion is not allowed'
```

or gets set back to "local"

```
storage: ""
```

```
storage: "{{ None }}"
```

```
storage: "{{ omit }}"



### Issue Type

Bug Report

### Component Name

community.general.proxmox

### Ansible Version

```console (paste below)
$ ansible --version
2.18.1
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
11.1.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

root@proxmox:~# pveversion
pve-manager/8.3.1/fb48e850ef9dde27 (running kernel: 6.8.12-5-pve)

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expect to create a linked clone LXC instance, however it can be seen from the logs that the clone is full:

```
root@proxmox:/var/log/pve/tasks# cat "./4/UPID:proxmox:00250CE2:06D80730:67748954:vzclone:118:root@pam:"
create full clone of mountpoint rootfs (local-lvm-thin:base-118-disk-0)
  Logical volume "vm-125-disk-0" created.
Creating filesystem with 4194304 4k blocks and 1048576 inodes
```

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
