### ISSUE TITLE
documentation proxmox_kvm on ide/scsi/sata gives incomplete allowed values

### ISSUE THREAD

**Issue by dirks** [ansible-collections/community.proxmox#93]
### Summary

In community.general version 9.5.8 the documentation of proxmox_kvm on the ide parameters says:

```
  ide:
    description:
      - A hash/dictionary of volume used as IDE hard disk or CD-ROM. O(ide='{"key":"value", "key":"value"}').
      - Keys allowed are - V(ide[n]) where 0 ≤ n ≤ 3.
      - Values allowed are - V("storage:size,format=value").
      - V(storage) is the storage identifier where to create the disk.
      - V(size) is the size of the disk in GB.
      - V(format) is the drive's backing file's data format. V(qcow2|raw|subvol). Please refer to the Proxmox VE Administrator
        Guide, section Proxmox VE Storage (see U(https://pve.proxmox.com/pve-docs/chapter-pvesm.html) for the latest version,
        tables 3 to 14) to find out format supported by the provided storage backend.
    type: dict
```

But the `ide:` examples have:

```yaml
    ide:
      ide2: 'local:cloudinit,format=qcow2'
```

As `cloudinit` is not really `size of the disk in GB` the allowed values in the description are incomplete. I guess the same is true for sata and scsi.

This raises the question, which other values are allowed? Can one specify a cd-rom as stated in the description? With and without inserted media, as in this example from api path https://proxmox.example.com/api2/json/nodes/node01/qemu/100/config

```
"ide2": "none,media=cdrom"
"ide3": "cephfs:iso/rhel-8.10-x86_64-dvd.iso,media=cdrom,size=13575M"
```

### Issue Type

Documentation Report

### Component Name

proxmox_kvm

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.18.6]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 07:44:25) [GCC 14.2.1 20250207] (/usr/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general
# /usr/lib/python3.13/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 10.7.0
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim

GALAXY_SERVERS:
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
